#!/usr/bin/env python3
"""
Convert all demo PNGs to LVGL C headers and generate demo_list.h.

Reads:  demos/*.png
Writes: resources/demos/<name>.h  (one per PNG)
        resources/demos/demo_list.h  (array of all demo images, for demo cycling)

Usage:
  python3 tools/gen_demos.py
  python3 tools/gen_demos.py --threshold 150

Run from the project root. Commit the generated headers before building.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from convert_image import image_to_lvgl_bytes, bytes_to_c_array

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed. Run: pip3 install Pillow", file=sys.stderr)
    sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--threshold', type=int, default=128,
                        help='Luminance cutoff for white pixel (0-255, default 128)')
    parser.add_argument('--src-dir', default='demos',
                        help='Directory containing demo PNGs (default: demos)')
    parser.add_argument('--out-dir', default='resources/demos',
                        help='Output directory for generated headers (default: resources/demos)')
    args = parser.parse_args()

    src_dir = Path(args.src_dir)
    out_dir = Path(args.out_dir)

    if not src_dir.exists():
        print(f"ERROR: source directory not found: {src_dir}", file=sys.stderr)
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)

    pngs = sorted(src_dir.glob('*.png'))
    if not pngs:
        print(f"No PNG files found in {src_dir}/")
        sys.exit(0)

    print(f"Converting {len(pngs)} PNG(s): {src_dir}/ -> {out_dir}/\n")

    var_names = []
    for png in pngs:
        var = png.stem.lower().replace(' ', '_').replace('-', '_')
        h_path = out_dir / f"{var}.h"

        img = Image.open(png)
        data, w, h = image_to_lvgl_bytes(img, args.threshold)

        content = '\n'.join([
            '#pragma once',
            '#include <lvgl.h>',
            f'// Generated from {png.name} by tools/gen_demos.py',
            '',
            bytes_to_c_array(data, var, w, h),
        ])
        h_path.write_text(content)
        print(f"  {png.name} ({w}x{h}) -> {h_path.name}  [{var}]")
        var_names.append(var)

    # Generate demo_list.h — includes all headers and exposes the image array
    list_path = out_dir / 'demo_list.h'
    lines = [
        '#pragma once',
        '#include <lvgl.h>',
        '// Generated by tools/gen_demos.py — do not edit manually',
        '',
    ]
    for var in var_names:
        lines.append(f'#include "{var}.h"')
    lines += [
        '',
        'static const lv_img_dsc_t *demo_images[] = {',
    ]
    for var in var_names:
        lines.append(f'    &{var},')
    lines += [
        '};',
        f'static const int demo_image_count = {len(var_names)};',
        '',
    ]
    list_path.write_text('\n'.join(lines))
    print(f"\n  demo_list.h -> {len(var_names)} image(s): {', '.join(var_names)}")
    print("\nDone. Commit the generated headers before building.")


if __name__ == '__main__':
    main()
