#pragma once
#include <lvgl.h>
// Generated by tools/gen_demos.py — do not edit manually

#include "all_small_font.h"
#include "mockup_3.h"
#include "mockup_4.h"
#include "font_size_test.h"

static const lv_img_dsc_t *demo_images[] = {
    &all_small_font,
    &mockup_3,
    &mockup_4,
    &font_size_test,
};
static const int demo_image_count = 4;
